sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
script:
  - mvn -f promagent-framework/pom.xml clean install
  - mvn -f promagent-example/pom-with-docker-tests.xml clean verify -Pwildfly 
  - mvn -f promagent-example/pom-with-docker-tests.xml clean verify -Pspring
